FROM ubuntu:22.04 AS runtime
RUN DEBIAN_FRONTEND=noninteractive apt-get update && \
    apt-get install -y --no-install-recommends\
    libboost-program-options1.74.0 \
    libreadline8 \
    libfmt8 \
    tcl \
    libspdlog1 \
    python3-numpy \
    python3-matplotlib \
    opensta \
    yosys && \
    apt-get clean

FROM runtime AS builder

RUN export DEBIAN_FRONTEND=noninteractive; \
    export DEBCONF_NONINTERACTIVE_SEEN=true; \
    echo 'tzdata tzdata/Areas select Etc' | debconf-set-selections; \
    echo 'tzdata tzdata/Zones/Etc select UTC' | debconf-set-selections; \
    apt-get update && \
    apt-get install -y tzdata \
        gcc-9 g++-9 \
        gcc-10 g++-10 \
        clang-11 \
        clang-12 \
        clang-13 \
        clang-14 \
        cmake \
        ccache \
        libboost-program-options1.74-dev \
        libreadline-dev \
        libpython3-dev \
        libgtest-dev \
        pybind11-dev \
        libspdlog-dev \
        libfmt-dev \
        lcov \
        gcovr \
        git \
        bison \
        make \
        tcl-dev \
        yosys-dev \
        opensta-dev \
        libpython3-dev \
        python3-distutils \
        swig \
        flex && \
    apt-get clean
ENV CC=gcc-10 CXX=g++-10

FROM builder AS compiled
RUN mkdir -p /LSOracle/build
COPY . /LSOracle/
WORKDIR /LSOracle

RUN cmake \
    -D CMAKE_BUILD_TYPE=RELEASE \
    -D ENABLE_OPENSTA=ON \
    -D OPENSTA_INCLUDE_DIR=/usr/include/OpenSTA \
    -D ENABLE_ABC=ON \
    -D YOSYS_PLUGIN=ON \
    -D YOSYS_INCLUDE_DIR=/usr/share/yosys/include \
    -D YOSYS_PLUGIN_DIR=/usr/share/yosys/plugins \
    -D LOCAL_PYBIND=OFF \
    -D LOCAL_SPDLOG=OFF \
    -D LOCAL_FMT=OFF \
    -D LOCAL_OPENSTA=OFF \
    -D LOCAL_BOOST=OFF \
    -D LOCAL_GTEST=OFF \
    -B build . && \
    cmake --build build -j$(nproc) && \
    cmake --install build

FROM runtime AS dist
COPY --from=compiled /usr/local/bin/lsoracle /usr/local/bin/lsoracle
COPY --from=compiled /usr/local/share/lsoracle/test.ini /usr/local/share/lsoracle/test.ini
COPY --from=compiled /usr/share/yosys/plugins/oracle.so /usr/share/yosys/plugins/oracle.so
CMD ["lsoracle"]
