#Build context must include both yosys and lsoracle directories; move this dockerfile or supply an appropriate context using -f during the build
FROM openroad/centos7-dev:latest
COPY yosys /yosys
COPY LSOracle /LSOracle/
WORKDIR /LSOracle
RUN source /opt/rh/devtoolset-8/enable && \
        cmake -B build -D CMAKE_BUILD_TYPE=RELEASE -D YOSYS_INCLUDE_DIR=/yosys -D YOSYS_PLUGIN=ON . && \
        cmake --build build -j$(nproc)
