# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.21

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/stow/cmake/cmake-3.21.1/bin/cmake

# The command to remove a file.
RM = /usr/local/stow/cmake/cmake-3.21.1/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/snelgrov/nas/lsoracle

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/snelgrov/nas/lsoracle

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/stow/cmake/cmake-3.21.1/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/stow/cmake/cmake-3.21.1/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/stow/cmake/cmake-3.21.1/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/stow/cmake/cmake-3.21.1/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/stow/cmake/cmake-3.21.1/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/stow/cmake/cmake-3.21.1/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/stow/cmake/cmake-3.21.1/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/stow/cmake/cmake-3.21.1/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/snelgrov/nas/lsoracle/CMakeFiles /home/snelgrov/nas/lsoracle//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/snelgrov/nas/lsoracle/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named gmock_main

# Build rule for target.
gmock_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock_main
.PHONY : gmock_main

# fast build rule for target.
gmock_main/fast:
	$(MAKE) $(MAKESILENT) -f lib/googletest/googlemock/CMakeFiles/gmock_main.dir/build.make lib/googletest/googlemock/CMakeFiles/gmock_main.dir/build
.PHONY : gmock_main/fast

#=============================================================================
# Target rules for targets named gmock

# Build rule for target.
gmock: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock
.PHONY : gmock

# fast build rule for target.
gmock/fast:
	$(MAKE) $(MAKESILENT) -f lib/googletest/googlemock/CMakeFiles/gmock.dir/build.make lib/googletest/googlemock/CMakeFiles/gmock.dir/build
.PHONY : gmock/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) $(MAKESILENT) -f lib/googletest/googletest/CMakeFiles/gtest_main.dir/build.make lib/googletest/googletest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) $(MAKESILENT) -f lib/googletest/googletest/CMakeFiles/gtest.dir/build.make lib/googletest/googletest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

#=============================================================================
# Target rules for targets named boost_container

# Build rule for target.
boost_container: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 boost_container
.PHONY : boost_container

# fast build rule for target.
boost_container/fast:
	$(MAKE) $(MAKESILENT) -f lib/boost/container/CMakeFiles/boost_container.dir/build.make lib/boost/container/CMakeFiles/boost_container.dir/build
.PHONY : boost_container/fast

#=============================================================================
# Target rules for targets named boost_exception

# Build rule for target.
boost_exception: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 boost_exception
.PHONY : boost_exception

# fast build rule for target.
boost_exception/fast:
	$(MAKE) $(MAKESILENT) -f lib/boost/exception/CMakeFiles/boost_exception.dir/build.make lib/boost/exception/CMakeFiles/boost_exception.dir/build
.PHONY : boost_exception/fast

#=============================================================================
# Target rules for targets named boost_program_options

# Build rule for target.
boost_program_options: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 boost_program_options
.PHONY : boost_program_options

# fast build rule for target.
boost_program_options/fast:
	$(MAKE) $(MAKESILENT) -f lib/boost/program_options/CMakeFiles/boost_program_options.dir/build.make lib/boost/program_options/CMakeFiles/boost_program_options.dir/build
.PHONY : boost_program_options/fast

#=============================================================================
# Target rules for targets named doc

# Build rule for target.
doc: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 doc
.PHONY : doc

# fast build rule for target.
doc/fast:
	$(MAKE) $(MAKESILENT) -f lib/kahypar/CMakeFiles/doc.dir/build.make lib/kahypar/CMakeFiles/doc.dir/build
.PHONY : doc/fast

#=============================================================================
# Target rules for targets named AnalyzeModifiedSources

# Build rule for target.
AnalyzeModifiedSources: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 AnalyzeModifiedSources
.PHONY : AnalyzeModifiedSources

# fast build rule for target.
AnalyzeModifiedSources/fast:
	$(MAKE) $(MAKESILENT) -f lib/kahypar/CMakeFiles/AnalyzeModifiedSources.dir/build.make lib/kahypar/CMakeFiles/AnalyzeModifiedSources.dir/build
.PHONY : AnalyzeModifiedSources/fast

#=============================================================================
# Target rules for targets named AnalyzeAllSources

# Build rule for target.
AnalyzeAllSources: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 AnalyzeAllSources
.PHONY : AnalyzeAllSources

# fast build rule for target.
AnalyzeAllSources/fast:
	$(MAKE) $(MAKESILENT) -f lib/kahypar/CMakeFiles/AnalyzeAllSources.dir/build.make lib/kahypar/CMakeFiles/AnalyzeAllSources.dir/build
.PHONY : AnalyzeAllSources/fast

#=============================================================================
# Target rules for targets named KaHyPar

# Build rule for target.
KaHyPar: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 KaHyPar
.PHONY : KaHyPar

# fast build rule for target.
KaHyPar/fast:
	$(MAKE) $(MAKESILENT) -f lib/kahypar/kahypar/application/CMakeFiles/KaHyPar.dir/build.make lib/kahypar/kahypar/application/CMakeFiles/KaHyPar.dir/build
.PHONY : KaHyPar/fast

#=============================================================================
# Target rules for targets named hgr_to_mtx_test

# Build rule for target.
hgr_to_mtx_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hgr_to_mtx_test
.PHONY : hgr_to_mtx_test

# fast build rule for target.
hgr_to_mtx_test/fast:
	$(MAKE) $(MAKESILENT) -f lib/kahypar/tools/CMakeFiles/hgr_to_mtx_test.dir/build.make lib/kahypar/tools/CMakeFiles/hgr_to_mtx_test.dir/build
.PHONY : hgr_to_mtx_test/fast

#=============================================================================
# Target rules for targets named hgr_to_edge_list_conversion_test

# Build rule for target.
hgr_to_edge_list_conversion_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hgr_to_edge_list_conversion_test
.PHONY : hgr_to_edge_list_conversion_test

# fast build rule for target.
hgr_to_edge_list_conversion_test/fast:
	$(MAKE) $(MAKESILENT) -f lib/kahypar/tools/CMakeFiles/hgr_to_edge_list_conversion_test.dir/build.make lib/kahypar/tools/CMakeFiles/hgr_to_edge_list_conversion_test.dir/build
.PHONY : hgr_to_edge_list_conversion_test/fast

#=============================================================================
# Target rules for targets named bookshelf_to_hgr_converter_test

# Build rule for target.
bookshelf_to_hgr_converter_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bookshelf_to_hgr_converter_test
.PHONY : bookshelf_to_hgr_converter_test

# fast build rule for target.
bookshelf_to_hgr_converter_test/fast:
	$(MAKE) $(MAKESILENT) -f lib/kahypar/tools/CMakeFiles/bookshelf_to_hgr_converter_test.dir/build.make lib/kahypar/tools/CMakeFiles/bookshelf_to_hgr_converter_test.dir/build
.PHONY : bookshelf_to_hgr_converter_test/fast

#=============================================================================
# Target rules for targets named HgrToBipartiteMetisGraph

# Build rule for target.
HgrToBipartiteMetisGraph: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 HgrToBipartiteMetisGraph
.PHONY : HgrToBipartiteMetisGraph

# fast build rule for target.
HgrToBipartiteMetisGraph/fast:
	$(MAKE) $(MAKESILENT) -f lib/kahypar/tools/CMakeFiles/HgrToBipartiteMetisGraph.dir/build.make lib/kahypar/tools/CMakeFiles/HgrToBipartiteMetisGraph.dir/build
.PHONY : HgrToBipartiteMetisGraph/fast

#=============================================================================
# Target rules for targets named HgrToHypergraphML

# Build rule for target.
HgrToHypergraphML: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 HgrToHypergraphML
.PHONY : HgrToHypergraphML

# fast build rule for target.
HgrToHypergraphML/fast:
	$(MAKE) $(MAKESILENT) -f lib/kahypar/tools/CMakeFiles/HgrToHypergraphML.dir/build.make lib/kahypar/tools/CMakeFiles/HgrToHypergraphML.dir/build
.PHONY : HgrToHypergraphML/fast

#=============================================================================
# Target rules for targets named repeats_to_hgr_conversion_test

# Build rule for target.
repeats_to_hgr_conversion_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 repeats_to_hgr_conversion_test
.PHONY : repeats_to_hgr_conversion_test

# fast build rule for target.
repeats_to_hgr_conversion_test/fast:
	$(MAKE) $(MAKESILENT) -f lib/kahypar/tools/CMakeFiles/repeats_to_hgr_conversion_test.dir/build.make lib/kahypar/tools/CMakeFiles/repeats_to_hgr_conversion_test.dir/build
.PHONY : repeats_to_hgr_conversion_test/fast

#=============================================================================
# Target rules for targets named HgrToPaToH

# Build rule for target.
HgrToPaToH: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 HgrToPaToH
.PHONY : HgrToPaToH

# fast build rule for target.
HgrToPaToH/fast:
	$(MAKE) $(MAKESILENT) -f lib/kahypar/tools/CMakeFiles/HgrToPaToH.dir/build.make lib/kahypar/tools/CMakeFiles/HgrToPaToH.dir/build
.PHONY : HgrToPaToH/fast

#=============================================================================
# Target rules for targets named HypergraphAnalyzer

# Build rule for target.
HypergraphAnalyzer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 HypergraphAnalyzer
.PHONY : HypergraphAnalyzer

# fast build rule for target.
HypergraphAnalyzer/fast:
	$(MAKE) $(MAKESILENT) -f lib/kahypar/tools/CMakeFiles/HypergraphAnalyzer.dir/build.make lib/kahypar/tools/CMakeFiles/HypergraphAnalyzer.dir/build
.PHONY : HypergraphAnalyzer/fast

#=============================================================================
# Target rules for targets named DegreePinDistribution

# Build rule for target.
DegreePinDistribution: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 DegreePinDistribution
.PHONY : DegreePinDistribution

# fast build rule for target.
DegreePinDistribution/fast:
	$(MAKE) $(MAKESILENT) -f lib/kahypar/tools/CMakeFiles/DegreePinDistribution.dir/build.make lib/kahypar/tools/CMakeFiles/DegreePinDistribution.dir/build
.PHONY : DegreePinDistribution/fast

#=============================================================================
# Target rules for targets named HypergraphStats

# Build rule for target.
HypergraphStats: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 HypergraphStats
.PHONY : HypergraphStats

# fast build rule for target.
HypergraphStats/fast:
	$(MAKE) $(MAKESILENT) -f lib/kahypar/tools/CMakeFiles/HypergraphStats.dir/build.make lib/kahypar/tools/CMakeFiles/HypergraphStats.dir/build
.PHONY : HypergraphStats/fast

#=============================================================================
# Target rules for targets named MtxToHgr

# Build rule for target.
MtxToHgr: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MtxToHgr
.PHONY : MtxToHgr

# fast build rule for target.
MtxToHgr/fast:
	$(MAKE) $(MAKESILENT) -f lib/kahypar/tools/CMakeFiles/MtxToHgr.dir/build.make lib/kahypar/tools/CMakeFiles/MtxToHgr.dir/build
.PHONY : MtxToHgr/fast

#=============================================================================
# Target rules for targets named HgrToBipartiteGraphML

# Build rule for target.
HgrToBipartiteGraphML: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 HgrToBipartiteGraphML
.PHONY : HgrToBipartiteGraphML

# fast build rule for target.
HgrToBipartiteGraphML/fast:
	$(MAKE) $(MAKESILENT) -f lib/kahypar/tools/CMakeFiles/HgrToBipartiteGraphML.dir/build.make lib/kahypar/tools/CMakeFiles/HgrToBipartiteGraphML.dir/build
.PHONY : HgrToBipartiteGraphML/fast

#=============================================================================
# Target rules for targets named cnf_to_hgr_converter_test

# Build rule for target.
cnf_to_hgr_converter_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cnf_to_hgr_converter_test
.PHONY : cnf_to_hgr_converter_test

# fast build rule for target.
cnf_to_hgr_converter_test/fast:
	$(MAKE) $(MAKESILENT) -f lib/kahypar/tools/CMakeFiles/cnf_to_hgr_converter_test.dir/build.make lib/kahypar/tools/CMakeFiles/cnf_to_hgr_converter_test.dir/build
.PHONY : cnf_to_hgr_converter_test/fast

#=============================================================================
# Target rules for targets named GraphToHgr

# Build rule for target.
GraphToHgr: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 GraphToHgr
.PHONY : GraphToHgr

# fast build rule for target.
GraphToHgr/fast:
	$(MAKE) $(MAKESILENT) -f lib/kahypar/tools/CMakeFiles/GraphToHgr.dir/build.make lib/kahypar/tools/CMakeFiles/GraphToHgr.dir/build
.PHONY : GraphToHgr/fast

#=============================================================================
# Target rules for targets named MtxToLAMAHgr

# Build rule for target.
MtxToLAMAHgr: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MtxToLAMAHgr
.PHONY : MtxToLAMAHgr

# fast build rule for target.
MtxToLAMAHgr/fast:
	$(MAKE) $(MAKESILENT) -f lib/kahypar/tools/CMakeFiles/MtxToLAMAHgr.dir/build.make lib/kahypar/tools/CMakeFiles/MtxToLAMAHgr.dir/build
.PHONY : MtxToLAMAHgr/fast

#=============================================================================
# Target rules for targets named CnfToHgr

# Build rule for target.
CnfToHgr: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CnfToHgr
.PHONY : CnfToHgr

# fast build rule for target.
CnfToHgr/fast:
	$(MAKE) $(MAKESILENT) -f lib/kahypar/tools/CMakeFiles/CnfToHgr.dir/build.make lib/kahypar/tools/CMakeFiles/CnfToHgr.dir/build
.PHONY : CnfToHgr/fast

#=============================================================================
# Target rules for targets named EvaluateMondriaanPartition

# Build rule for target.
EvaluateMondriaanPartition: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 EvaluateMondriaanPartition
.PHONY : EvaluateMondriaanPartition

# fast build rule for target.
EvaluateMondriaanPartition/fast:
	$(MAKE) $(MAKESILENT) -f lib/kahypar/tools/CMakeFiles/EvaluateMondriaanPartition.dir/build.make lib/kahypar/tools/CMakeFiles/EvaluateMondriaanPartition.dir/build
.PHONY : EvaluateMondriaanPartition/fast

#=============================================================================
# Target rules for targets named BookshelfToHgr

# Build rule for target.
BookshelfToHgr: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 BookshelfToHgr
.PHONY : BookshelfToHgr

# fast build rule for target.
BookshelfToHgr/fast:
	$(MAKE) $(MAKESILENT) -f lib/kahypar/tools/CMakeFiles/BookshelfToHgr.dir/build.make lib/kahypar/tools/CMakeFiles/BookshelfToHgr.dir/build
.PHONY : BookshelfToHgr/fast

#=============================================================================
# Target rules for targets named VerifyPartition

# Build rule for target.
VerifyPartition: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 VerifyPartition
.PHONY : VerifyPartition

# fast build rule for target.
VerifyPartition/fast:
	$(MAKE) $(MAKESILENT) -f lib/kahypar/tools/CMakeFiles/VerifyPartition.dir/build.make lib/kahypar/tools/CMakeFiles/VerifyPartition.dir/build
.PHONY : VerifyPartition/fast

#=============================================================================
# Target rules for targets named mtx_to_hgr_converter_test

# Build rule for target.
mtx_to_hgr_converter_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mtx_to_hgr_converter_test
.PHONY : mtx_to_hgr_converter_test

# fast build rule for target.
mtx_to_hgr_converter_test/fast:
	$(MAKE) $(MAKESILENT) -f lib/kahypar/tools/CMakeFiles/mtx_to_hgr_converter_test.dir/build.make lib/kahypar/tools/CMakeFiles/mtx_to_hgr_converter_test.dir/build
.PHONY : mtx_to_hgr_converter_test/fast

#=============================================================================
# Target rules for targets named CreateWeightedHgr

# Build rule for target.
CreateWeightedHgr: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CreateWeightedHgr
.PHONY : CreateWeightedHgr

# fast build rule for target.
CreateWeightedHgr/fast:
	$(MAKE) $(MAKESILENT) -f lib/kahypar/tools/CMakeFiles/CreateWeightedHgr.dir/build.make lib/kahypar/tools/CMakeFiles/CreateWeightedHgr.dir/build
.PHONY : CreateWeightedHgr/fast

#=============================================================================
# Target rules for targets named RepeatsToHgr

# Build rule for target.
RepeatsToHgr: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 RepeatsToHgr
.PHONY : RepeatsToHgr

# fast build rule for target.
RepeatsToHgr/fast:
	$(MAKE) $(MAKESILENT) -f lib/kahypar/tools/CMakeFiles/RepeatsToHgr.dir/build.make lib/kahypar/tools/CMakeFiles/RepeatsToHgr.dir/build
.PHONY : RepeatsToHgr/fast

#=============================================================================
# Target rules for targets named HgrToMondriaanMtx

# Build rule for target.
HgrToMondriaanMtx: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 HgrToMondriaanMtx
.PHONY : HgrToMondriaanMtx

# fast build rule for target.
HgrToMondriaanMtx/fast:
	$(MAKE) $(MAKESILENT) -f lib/kahypar/tools/CMakeFiles/HgrToMondriaanMtx.dir/build.make lib/kahypar/tools/CMakeFiles/HgrToMondriaanMtx.dir/build
.PHONY : HgrToMondriaanMtx/fast

#=============================================================================
# Target rules for targets named ComputeNeighborHoodSizes

# Build rule for target.
ComputeNeighborHoodSizes: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ComputeNeighborHoodSizes
.PHONY : ComputeNeighborHoodSizes

# fast build rule for target.
ComputeNeighborHoodSizes/fast:
	$(MAKE) $(MAKESILENT) -f lib/kahypar/tools/CMakeFiles/ComputeNeighborHoodSizes.dir/build.make lib/kahypar/tools/CMakeFiles/ComputeNeighborHoodSizes.dir/build
.PHONY : ComputeNeighborHoodSizes/fast

#=============================================================================
# Target rules for targets named HgrToEdgeList

# Build rule for target.
HgrToEdgeList: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 HgrToEdgeList
.PHONY : HgrToEdgeList

# fast build rule for target.
HgrToEdgeList/fast:
	$(MAKE) $(MAKESILENT) -f lib/kahypar/tools/CMakeFiles/HgrToEdgeList.dir/build.make lib/kahypar/tools/CMakeFiles/HgrToEdgeList.dir/build
.PHONY : HgrToEdgeList/fast

#=============================================================================
# Target rules for targets named RemoveHeavyNodes

# Build rule for target.
RemoveHeavyNodes: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 RemoveHeavyNodes
.PHONY : RemoveHeavyNodes

# fast build rule for target.
RemoveHeavyNodes/fast:
	$(MAKE) $(MAKESILENT) -f lib/kahypar/tools/CMakeFiles/RemoveHeavyNodes.dir/build.make lib/kahypar/tools/CMakeFiles/RemoveHeavyNodes.dir/build
.PHONY : RemoveHeavyNodes/fast

#=============================================================================
# Target rules for targets named HgrToMtx

# Build rule for target.
HgrToMtx: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 HgrToMtx
.PHONY : HgrToMtx

# fast build rule for target.
HgrToMtx/fast:
	$(MAKE) $(MAKESILENT) -f lib/kahypar/tools/CMakeFiles/HgrToMtx.dir/build.make lib/kahypar/tools/CMakeFiles/HgrToMtx.dir/build
.PHONY : HgrToMtx/fast

#=============================================================================
# Target rules for targets named CalculateRelaxedEpsilon

# Build rule for target.
CalculateRelaxedEpsilon: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CalculateRelaxedEpsilon
.PHONY : CalculateRelaxedEpsilon

# fast build rule for target.
CalculateRelaxedEpsilon/fast:
	$(MAKE) $(MAKESILENT) -f lib/kahypar/tools/CMakeFiles/CalculateRelaxedEpsilon.dir/build.make lib/kahypar/tools/CMakeFiles/CalculateRelaxedEpsilon.dir/build
.PHONY : CalculateRelaxedEpsilon/fast

#=============================================================================
# Target rules for targets named uninstall-kahypar

# Build rule for target.
uninstall-kahypar: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 uninstall-kahypar
.PHONY : uninstall-kahypar

# fast build rule for target.
uninstall-kahypar/fast:
	$(MAKE) $(MAKESILENT) -f lib/kahypar/lib/CMakeFiles/uninstall-kahypar.dir/build.make lib/kahypar/lib/CMakeFiles/uninstall-kahypar.dir/build
.PHONY : uninstall-kahypar/fast

#=============================================================================
# Target rules for targets named kahypar

# Build rule for target.
kahypar: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 kahypar
.PHONY : kahypar

# fast build rule for target.
kahypar/fast:
	$(MAKE) $(MAKESILENT) -f lib/kahypar/lib/CMakeFiles/kahypar.dir/build.make lib/kahypar/lib/CMakeFiles/kahypar.dir/build
.PHONY : kahypar/fast

#=============================================================================
# Target rules for targets named install.library

# Build rule for target.
install.library: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 install.library
.PHONY : install.library

# fast build rule for target.
install.library/fast:
	$(MAKE) $(MAKESILENT) -f lib/kahypar/lib/CMakeFiles/install.library.dir/build.make lib/kahypar/lib/CMakeFiles/install.library.dir/build
.PHONY : install.library/fast

#=============================================================================
# Target rules for targets named probability_table_test

# Build rule for target.
probability_table_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 probability_table_test
.PHONY : probability_table_test

# fast build rule for target.
probability_table_test/fast:
	$(MAKE) $(MAKESILENT) -f lib/kahypar/tests/partition/evolutionary/CMakeFiles/probability_table_test.dir/build.make lib/kahypar/tests/partition/evolutionary/CMakeFiles/probability_table_test.dir/build
.PHONY : probability_table_test/fast

#=============================================================================
# Target rules for targets named individual_test

# Build rule for target.
individual_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 individual_test
.PHONY : individual_test

# fast build rule for target.
individual_test/fast:
	$(MAKE) $(MAKESILENT) -f lib/kahypar/tests/partition/evolutionary/CMakeFiles/individual_test.dir/build.make lib/kahypar/tests/partition/evolutionary/CMakeFiles/individual_test.dir/build
.PHONY : individual_test/fast

#=============================================================================
# Target rules for targets named population_test

# Build rule for target.
population_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 population_test
.PHONY : population_test

# fast build rule for target.
population_test/fast:
	$(MAKE) $(MAKESILENT) -f lib/kahypar/tests/partition/evolutionary/CMakeFiles/population_test.dir/build.make lib/kahypar/tests/partition/evolutionary/CMakeFiles/population_test.dir/build
.PHONY : population_test/fast

#=============================================================================
# Target rules for targets named edge_frequency_test

# Build rule for target.
edge_frequency_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 edge_frequency_test
.PHONY : edge_frequency_test

# fast build rule for target.
edge_frequency_test/fast:
	$(MAKE) $(MAKESILENT) -f lib/kahypar/tests/partition/evolutionary/CMakeFiles/edge_frequency_test.dir/build.make lib/kahypar/tests/partition/evolutionary/CMakeFiles/edge_frequency_test.dir/build
.PHONY : edge_frequency_test/fast

#=============================================================================
# Target rules for targets named mutation_test

# Build rule for target.
mutation_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mutation_test
.PHONY : mutation_test

# fast build rule for target.
mutation_test/fast:
	$(MAKE) $(MAKESILENT) -f lib/kahypar/tests/partition/evolutionary/CMakeFiles/mutation_test.dir/build.make lib/kahypar/tests/partition/evolutionary/CMakeFiles/mutation_test.dir/build
.PHONY : mutation_test/fast

#=============================================================================
# Target rules for targets named evo_partitioner_test

# Build rule for target.
evo_partitioner_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 evo_partitioner_test
.PHONY : evo_partitioner_test

# fast build rule for target.
evo_partitioner_test/fast:
	$(MAKE) $(MAKESILENT) -f lib/kahypar/tests/partition/evolutionary/CMakeFiles/evo_partitioner_test.dir/build.make lib/kahypar/tests/partition/evolutionary/CMakeFiles/evo_partitioner_test.dir/build
.PHONY : evo_partitioner_test/fast

#=============================================================================
# Target rules for targets named combine_test

# Build rule for target.
combine_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 combine_test
.PHONY : combine_test

# fast build rule for target.
combine_test/fast:
	$(MAKE) $(MAKESILENT) -f lib/kahypar/tests/partition/evolutionary/CMakeFiles/combine_test.dir/build.make lib/kahypar/tests/partition/evolutionary/CMakeFiles/combine_test.dir/build
.PHONY : combine_test/fast

#=============================================================================
# Target rules for targets named static_multi_dispatch_factory_test

# Build rule for target.
static_multi_dispatch_factory_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 static_multi_dispatch_factory_test
.PHONY : static_multi_dispatch_factory_test

# fast build rule for target.
static_multi_dispatch_factory_test/fast:
	$(MAKE) $(MAKESILENT) -f lib/kahypar/tests/meta/CMakeFiles/static_multi_dispatch_factory_test.dir/build.make lib/kahypar/tests/meta/CMakeFiles/static_multi_dispatch_factory_test.dir/build
.PHONY : static_multi_dispatch_factory_test/fast

#=============================================================================
# Target rules for targets named integration_tests

# Build rule for target.
integration_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 integration_tests
.PHONY : integration_tests

# fast build rule for target.
integration_tests/fast:
	$(MAKE) $(MAKESILENT) -f lib/kahypar/tests/end_to_end/CMakeFiles/integration_tests.dir/build.make lib/kahypar/tests/end_to_end/CMakeFiles/integration_tests.dir/build
.PHONY : integration_tests/fast

#=============================================================================
# Target rules for targets named regression_tests

# Build rule for target.
regression_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 regression_tests
.PHONY : regression_tests

# fast build rule for target.
regression_tests/fast:
	$(MAKE) $(MAKESILENT) -f lib/kahypar/tests/regression/CMakeFiles/regression_tests.dir/build.make lib/kahypar/tests/regression/CMakeFiles/regression_tests.dir/build
.PHONY : regression_tests/fast

#=============================================================================
# Target rules for targets named kway_priority_queue_test

# Build rule for target.
kway_priority_queue_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 kway_priority_queue_test
.PHONY : kway_priority_queue_test

# fast build rule for target.
kway_priority_queue_test/fast:
	$(MAKE) $(MAKESILENT) -f lib/kahypar/tests/datastructure/CMakeFiles/kway_priority_queue_test.dir/build.make lib/kahypar/tests/datastructure/CMakeFiles/kway_priority_queue_test.dir/build
.PHONY : kway_priority_queue_test/fast

#=============================================================================
# Target rules for targets named priority_queue_test

# Build rule for target.
priority_queue_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 priority_queue_test
.PHONY : priority_queue_test

# fast build rule for target.
priority_queue_test/fast:
	$(MAKE) $(MAKESILENT) -f lib/kahypar/tests/datastructure/CMakeFiles/priority_queue_test.dir/build.make lib/kahypar/tests/datastructure/CMakeFiles/priority_queue_test.dir/build
.PHONY : priority_queue_test/fast

#=============================================================================
# Target rules for targets named graph_test

# Build rule for target.
graph_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 graph_test
.PHONY : graph_test

# fast build rule for target.
graph_test/fast:
	$(MAKE) $(MAKESILENT) -f lib/kahypar/tests/datastructure/CMakeFiles/graph_test.dir/build.make lib/kahypar/tests/datastructure/CMakeFiles/graph_test.dir/build
.PHONY : graph_test/fast

#=============================================================================
# Target rules for targets named hypergraph_test

# Build rule for target.
hypergraph_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hypergraph_test
.PHONY : hypergraph_test

# fast build rule for target.
hypergraph_test/fast:
	$(MAKE) $(MAKESILENT) -f lib/kahypar/tests/datastructure/CMakeFiles/hypergraph_test.dir/build.make lib/kahypar/tests/datastructure/CMakeFiles/hypergraph_test.dir/build
.PHONY : hypergraph_test/fast

#=============================================================================
# Target rules for targets named sparse_set_test

# Build rule for target.
sparse_set_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sparse_set_test
.PHONY : sparse_set_test

# fast build rule for target.
sparse_set_test/fast:
	$(MAKE) $(MAKESILENT) -f lib/kahypar/tests/datastructure/CMakeFiles/sparse_set_test.dir/build.make lib/kahypar/tests/datastructure/CMakeFiles/sparse_set_test.dir/build
.PHONY : sparse_set_test/fast

#=============================================================================
# Target rules for targets named sparse_map_test

# Build rule for target.
sparse_map_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sparse_map_test
.PHONY : sparse_map_test

# fast build rule for target.
sparse_map_test/fast:
	$(MAKE) $(MAKESILENT) -f lib/kahypar/tests/datastructure/CMakeFiles/sparse_map_test.dir/build.make lib/kahypar/tests/datastructure/CMakeFiles/sparse_map_test.dir/build
.PHONY : sparse_map_test/fast

#=============================================================================
# Target rules for targets named binary_heap_test

# Build rule for target.
binary_heap_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 binary_heap_test
.PHONY : binary_heap_test

# fast build rule for target.
binary_heap_test/fast:
	$(MAKE) $(MAKESILENT) -f lib/kahypar/tests/datastructure/CMakeFiles/binary_heap_test.dir/build.make lib/kahypar/tests/datastructure/CMakeFiles/binary_heap_test.dir/build
.PHONY : binary_heap_test/fast

#=============================================================================
# Target rules for targets named hypergraph_io_test

# Build rule for target.
hypergraph_io_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hypergraph_io_test
.PHONY : hypergraph_io_test

# fast build rule for target.
hypergraph_io_test/fast:
	$(MAKE) $(MAKESILENT) -f lib/kahypar/tests/io/CMakeFiles/hypergraph_io_test.dir/build.make lib/kahypar/tests/io/CMakeFiles/hypergraph_io_test.dir/build
.PHONY : hypergraph_io_test/fast

#=============================================================================
# Target rules for targets named interface_test

# Build rule for target.
interface_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 interface_test
.PHONY : interface_test

# fast build rule for target.
interface_test/fast:
	$(MAKE) $(MAKESILENT) -f lib/kahypar/tests/interface/CMakeFiles/interface_test.dir/build.make lib/kahypar/tests/interface/CMakeFiles/interface_test.dir/build
.PHONY : interface_test/fast

#=============================================================================
# Target rules for targets named math_test

# Build rule for target.
math_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 math_test
.PHONY : math_test

# fast build rule for target.
math_test/fast:
	$(MAKE) $(MAKESILENT) -f lib/kahypar/tests/utils/CMakeFiles/math_test.dir/build.make lib/kahypar/tests/utils/CMakeFiles/math_test.dir/build
.PHONY : math_test/fast

#=============================================================================
# Target rules for targets named partitioner_test

# Build rule for target.
partitioner_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 partitioner_test
.PHONY : partitioner_test

# fast build rule for target.
partitioner_test/fast:
	$(MAKE) $(MAKESILENT) -f lib/kahypar/tests/partition/CMakeFiles/partitioner_test.dir/build.make lib/kahypar/tests/partition/CMakeFiles/partitioner_test.dir/build
.PHONY : partitioner_test/fast

#=============================================================================
# Target rules for targets named fixed_vertex_test

# Build rule for target.
fixed_vertex_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fixed_vertex_test
.PHONY : fixed_vertex_test

# fast build rule for target.
fixed_vertex_test/fast:
	$(MAKE) $(MAKESILENT) -f lib/kahypar/tests/partition/CMakeFiles/fixed_vertex_test.dir/build.make lib/kahypar/tests/partition/CMakeFiles/fixed_vertex_test.dir/build
.PHONY : fixed_vertex_test/fast

#=============================================================================
# Target rules for targets named metrics_test

# Build rule for target.
metrics_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 metrics_test
.PHONY : metrics_test

# fast build rule for target.
metrics_test/fast:
	$(MAKE) $(MAKESILENT) -f lib/kahypar/tests/partition/CMakeFiles/metrics_test.dir/build.make lib/kahypar/tests/partition/CMakeFiles/metrics_test.dir/build
.PHONY : metrics_test/fast

#=============================================================================
# Target rules for targets named louvain_test

# Build rule for target.
louvain_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 louvain_test
.PHONY : louvain_test

# fast build rule for target.
louvain_test/fast:
	$(MAKE) $(MAKESILENT) -f lib/kahypar/tests/partition/preprocessing/CMakeFiles/louvain_test.dir/build.make lib/kahypar/tests/partition/preprocessing/CMakeFiles/louvain_test.dir/build
.PHONY : louvain_test/fast

#=============================================================================
# Target rules for targets named sparsifier_test

# Build rule for target.
sparsifier_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sparsifier_test
.PHONY : sparsifier_test

# fast build rule for target.
sparsifier_test/fast:
	$(MAKE) $(MAKESILENT) -f lib/kahypar/tests/partition/preprocessing/CMakeFiles/sparsifier_test.dir/build.make lib/kahypar/tests/partition/preprocessing/CMakeFiles/sparsifier_test.dir/build
.PHONY : sparsifier_test/fast

#=============================================================================
# Target rules for targets named hypergraph_deduplicator_test

# Build rule for target.
hypergraph_deduplicator_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hypergraph_deduplicator_test
.PHONY : hypergraph_deduplicator_test

# fast build rule for target.
hypergraph_deduplicator_test/fast:
	$(MAKE) $(MAKESILENT) -f lib/kahypar/tests/partition/preprocessing/CMakeFiles/hypergraph_deduplicator_test.dir/build.make lib/kahypar/tests/partition/preprocessing/CMakeFiles/hypergraph_deduplicator_test.dir/build
.PHONY : hypergraph_deduplicator_test/fast

#=============================================================================
# Target rules for targets named full_vertex_pair_coarsener_test

# Build rule for target.
full_vertex_pair_coarsener_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 full_vertex_pair_coarsener_test
.PHONY : full_vertex_pair_coarsener_test

# fast build rule for target.
full_vertex_pair_coarsener_test/fast:
	$(MAKE) $(MAKESILENT) -f lib/kahypar/tests/partition/coarsening/CMakeFiles/full_vertex_pair_coarsener_test.dir/build.make lib/kahypar/tests/partition/coarsening/CMakeFiles/full_vertex_pair_coarsener_test.dir/build
.PHONY : full_vertex_pair_coarsener_test/fast

#=============================================================================
# Target rules for targets named lazy_vertex_pair_coarsener_test

# Build rule for target.
lazy_vertex_pair_coarsener_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lazy_vertex_pair_coarsener_test
.PHONY : lazy_vertex_pair_coarsener_test

# fast build rule for target.
lazy_vertex_pair_coarsener_test/fast:
	$(MAKE) $(MAKESILENT) -f lib/kahypar/tests/partition/coarsening/CMakeFiles/lazy_vertex_pair_coarsener_test.dir/build.make lib/kahypar/tests/partition/coarsening/CMakeFiles/lazy_vertex_pair_coarsener_test.dir/build
.PHONY : lazy_vertex_pair_coarsener_test/fast

#=============================================================================
# Target rules for targets named vertex_pair_rater_test

# Build rule for target.
vertex_pair_rater_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 vertex_pair_rater_test
.PHONY : vertex_pair_rater_test

# fast build rule for target.
vertex_pair_rater_test/fast:
	$(MAKE) $(MAKESILENT) -f lib/kahypar/tests/partition/coarsening/CMakeFiles/vertex_pair_rater_test.dir/build.make lib/kahypar/tests/partition/coarsening/CMakeFiles/vertex_pair_rater_test.dir/build
.PHONY : vertex_pair_rater_test/fast

#=============================================================================
# Target rules for targets named random_partitioner_test

# Build rule for target.
random_partitioner_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 random_partitioner_test
.PHONY : random_partitioner_test

# fast build rule for target.
random_partitioner_test/fast:
	$(MAKE) $(MAKESILENT) -f lib/kahypar/tests/partition/initial_partitioning/CMakeFiles/random_partitioner_test.dir/build.make lib/kahypar/tests/partition/initial_partitioning/CMakeFiles/random_partitioner_test.dir/build
.PHONY : random_partitioner_test/fast

#=============================================================================
# Target rules for targets named initial_partitioner_base_test

# Build rule for target.
initial_partitioner_base_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 initial_partitioner_base_test
.PHONY : initial_partitioner_base_test

# fast build rule for target.
initial_partitioner_base_test/fast:
	$(MAKE) $(MAKESILENT) -f lib/kahypar/tests/partition/initial_partitioning/CMakeFiles/initial_partitioner_base_test.dir/build.make lib/kahypar/tests/partition/initial_partitioning/CMakeFiles/initial_partitioner_base_test.dir/build
.PHONY : initial_partitioner_base_test/fast

#=============================================================================
# Target rules for targets named greedy_queue_selection_test

# Build rule for target.
greedy_queue_selection_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 greedy_queue_selection_test
.PHONY : greedy_queue_selection_test

# fast build rule for target.
greedy_queue_selection_test/fast:
	$(MAKE) $(MAKESILENT) -f lib/kahypar/tests/partition/initial_partitioning/CMakeFiles/greedy_queue_selection_test.dir/build.make lib/kahypar/tests/partition/initial_partitioning/CMakeFiles/greedy_queue_selection_test.dir/build
.PHONY : greedy_queue_selection_test/fast

#=============================================================================
# Target rules for targets named greedy_hypergraph_growing_functionality_test

# Build rule for target.
greedy_hypergraph_growing_functionality_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 greedy_hypergraph_growing_functionality_test
.PHONY : greedy_hypergraph_growing_functionality_test

# fast build rule for target.
greedy_hypergraph_growing_functionality_test/fast:
	$(MAKE) $(MAKESILENT) -f lib/kahypar/tests/partition/initial_partitioning/CMakeFiles/greedy_hypergraph_growing_functionality_test.dir/build.make lib/kahypar/tests/partition/initial_partitioning/CMakeFiles/greedy_hypergraph_growing_functionality_test.dir/build
.PHONY : greedy_hypergraph_growing_functionality_test/fast

#=============================================================================
# Target rules for targets named gain_computation_test

# Build rule for target.
gain_computation_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gain_computation_test
.PHONY : gain_computation_test

# fast build rule for target.
gain_computation_test/fast:
	$(MAKE) $(MAKESILENT) -f lib/kahypar/tests/partition/initial_partitioning/CMakeFiles/gain_computation_test.dir/build.make lib/kahypar/tests/partition/initial_partitioning/CMakeFiles/gain_computation_test.dir/build
.PHONY : gain_computation_test/fast

#=============================================================================
# Target rules for targets named label_propagation_partitioner_test

# Build rule for target.
label_propagation_partitioner_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 label_propagation_partitioner_test
.PHONY : label_propagation_partitioner_test

# fast build rule for target.
label_propagation_partitioner_test/fast:
	$(MAKE) $(MAKESILENT) -f lib/kahypar/tests/partition/initial_partitioning/CMakeFiles/label_propagation_partitioner_test.dir/build.make lib/kahypar/tests/partition/initial_partitioning/CMakeFiles/label_propagation_partitioner_test.dir/build
.PHONY : label_propagation_partitioner_test/fast

#=============================================================================
# Target rules for targets named greedy_hypergraph_growing_partitioner_test

# Build rule for target.
greedy_hypergraph_growing_partitioner_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 greedy_hypergraph_growing_partitioner_test
.PHONY : greedy_hypergraph_growing_partitioner_test

# fast build rule for target.
greedy_hypergraph_growing_partitioner_test/fast:
	$(MAKE) $(MAKESILENT) -f lib/kahypar/tests/partition/initial_partitioning/CMakeFiles/greedy_hypergraph_growing_partitioner_test.dir/build.make lib/kahypar/tests/partition/initial_partitioning/CMakeFiles/greedy_hypergraph_growing_partitioner_test.dir/build
.PHONY : greedy_hypergraph_growing_partitioner_test/fast

#=============================================================================
# Target rules for targets named bfs_partitioner_test

# Build rule for target.
bfs_partitioner_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bfs_partitioner_test
.PHONY : bfs_partitioner_test

# fast build rule for target.
bfs_partitioner_test/fast:
	$(MAKE) $(MAKESILENT) -f lib/kahypar/tests/partition/initial_partitioning/CMakeFiles/bfs_partitioner_test.dir/build.make lib/kahypar/tests/partition/initial_partitioning/CMakeFiles/bfs_partitioner_test.dir/build
.PHONY : bfs_partitioner_test/fast

#=============================================================================
# Target rules for targets named label_propagation_functionality_test

# Build rule for target.
label_propagation_functionality_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 label_propagation_functionality_test
.PHONY : label_propagation_functionality_test

# fast build rule for target.
label_propagation_functionality_test/fast:
	$(MAKE) $(MAKESILENT) -f lib/kahypar/tests/partition/initial_partitioning/CMakeFiles/label_propagation_functionality_test.dir/build.make lib/kahypar/tests/partition/initial_partitioning/CMakeFiles/label_propagation_functionality_test.dir/build
.PHONY : label_propagation_functionality_test/fast

#=============================================================================
# Target rules for targets named two_way_fm_refiner_test

# Build rule for target.
two_way_fm_refiner_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 two_way_fm_refiner_test
.PHONY : two_way_fm_refiner_test

# fast build rule for target.
two_way_fm_refiner_test/fast:
	$(MAKE) $(MAKESILENT) -f lib/kahypar/tests/partition/refinement/CMakeFiles/two_way_fm_refiner_test.dir/build.make lib/kahypar/tests/partition/refinement/CMakeFiles/two_way_fm_refiner_test.dir/build
.PHONY : two_way_fm_refiner_test/fast

#=============================================================================
# Target rules for targets named k_way_fm_refiner_test

# Build rule for target.
k_way_fm_refiner_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 k_way_fm_refiner_test
.PHONY : k_way_fm_refiner_test

# fast build rule for target.
k_way_fm_refiner_test/fast:
	$(MAKE) $(MAKESILENT) -f lib/kahypar/tests/partition/refinement/CMakeFiles/k_way_fm_refiner_test.dir/build.make lib/kahypar/tests/partition/refinement/CMakeFiles/k_way_fm_refiner_test.dir/build
.PHONY : k_way_fm_refiner_test/fast

#=============================================================================
# Target rules for targets named quotient_graph_block_scheduler_test

# Build rule for target.
quotient_graph_block_scheduler_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 quotient_graph_block_scheduler_test
.PHONY : quotient_graph_block_scheduler_test

# fast build rule for target.
quotient_graph_block_scheduler_test/fast:
	$(MAKE) $(MAKESILENT) -f lib/kahypar/tests/partition/refinement/CMakeFiles/quotient_graph_block_scheduler_test.dir/build.make lib/kahypar/tests/partition/refinement/CMakeFiles/quotient_graph_block_scheduler_test.dir/build
.PHONY : quotient_graph_block_scheduler_test/fast

#=============================================================================
# Target rules for targets named kahypar_python

# Build rule for target.
kahypar_python: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 kahypar_python
.PHONY : kahypar_python

# fast build rule for target.
kahypar_python/fast:
	$(MAKE) $(MAKESILENT) -f lib/kahypar/python/CMakeFiles/kahypar_python.dir/build.make lib/kahypar/python/CMakeFiles/kahypar_python.dir/build
.PHONY : kahypar_python/fast

#=============================================================================
# Target rules for targets named libabcsat

# Build rule for target.
libabcsat: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libabcsat
.PHONY : libabcsat

# fast build rule for target.
libabcsat/fast:
	$(MAKE) $(MAKESILENT) -f lib/mockturtle/lib/abcsat/CMakeFiles/libabcsat.dir/build.make lib/mockturtle/lib/abcsat/CMakeFiles/libabcsat.dir/build
.PHONY : libabcsat/fast

#=============================================================================
# Target rules for targets named libabcesop

# Build rule for target.
libabcesop: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libabcesop
.PHONY : libabcesop

# fast build rule for target.
libabcesop/fast:
	$(MAKE) $(MAKESILENT) -f lib/mockturtle/lib/abcesop/CMakeFiles/libabcesop.dir/build.make lib/mockturtle/lib/abcesop/CMakeFiles/libabcesop.dir/build
.PHONY : libabcesop/fast

#=============================================================================
# Target rules for targets named cut_enumeration

# Build rule for target.
cut_enumeration: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cut_enumeration
.PHONY : cut_enumeration

# fast build rule for target.
cut_enumeration/fast:
	$(MAKE) $(MAKESILENT) -f lib/mockturtle/examples/CMakeFiles/cut_enumeration.dir/build.make lib/mockturtle/examples/CMakeFiles/cut_enumeration.dir/build
.PHONY : cut_enumeration/fast

#=============================================================================
# Target rules for targets named unit_tests

# Build rule for target.
unit_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 unit_tests
.PHONY : unit_tests

# fast build rule for target.
unit_tests/fast:
	$(MAKE) $(MAKESILENT) -f core/CMakeFiles/unit_tests.dir/build.make core/CMakeFiles/unit_tests.dir/build
.PHONY : unit_tests/fast

#=============================================================================
# Target rules for targets named lsoracle

# Build rule for target.
lsoracle: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lsoracle
.PHONY : lsoracle

# fast build rule for target.
lsoracle/fast:
	$(MAKE) $(MAKESILENT) -f core/CMakeFiles/lsoracle.dir/build.make core/CMakeFiles/lsoracle.dir/build
.PHONY : lsoracle/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... AnalyzeAllSources"
	@echo "... AnalyzeModifiedSources"
	@echo "... doc"
	@echo "... install.library"
	@echo "... uninstall-kahypar"
	@echo "... BookshelfToHgr"
	@echo "... CalculateRelaxedEpsilon"
	@echo "... CnfToHgr"
	@echo "... ComputeNeighborHoodSizes"
	@echo "... CreateWeightedHgr"
	@echo "... DegreePinDistribution"
	@echo "... EvaluateMondriaanPartition"
	@echo "... GraphToHgr"
	@echo "... HgrToBipartiteGraphML"
	@echo "... HgrToBipartiteMetisGraph"
	@echo "... HgrToEdgeList"
	@echo "... HgrToHypergraphML"
	@echo "... HgrToMondriaanMtx"
	@echo "... HgrToMtx"
	@echo "... HgrToPaToH"
	@echo "... HypergraphAnalyzer"
	@echo "... HypergraphStats"
	@echo "... KaHyPar"
	@echo "... MtxToHgr"
	@echo "... MtxToLAMAHgr"
	@echo "... RemoveHeavyNodes"
	@echo "... RepeatsToHgr"
	@echo "... VerifyPartition"
	@echo "... bfs_partitioner_test"
	@echo "... binary_heap_test"
	@echo "... bookshelf_to_hgr_converter_test"
	@echo "... boost_container"
	@echo "... boost_exception"
	@echo "... boost_program_options"
	@echo "... cnf_to_hgr_converter_test"
	@echo "... combine_test"
	@echo "... cut_enumeration"
	@echo "... edge_frequency_test"
	@echo "... evo_partitioner_test"
	@echo "... fixed_vertex_test"
	@echo "... full_vertex_pair_coarsener_test"
	@echo "... gain_computation_test"
	@echo "... gmock"
	@echo "... gmock_main"
	@echo "... graph_test"
	@echo "... greedy_hypergraph_growing_functionality_test"
	@echo "... greedy_hypergraph_growing_partitioner_test"
	@echo "... greedy_queue_selection_test"
	@echo "... gtest"
	@echo "... gtest_main"
	@echo "... hgr_to_edge_list_conversion_test"
	@echo "... hgr_to_mtx_test"
	@echo "... hypergraph_deduplicator_test"
	@echo "... hypergraph_io_test"
	@echo "... hypergraph_test"
	@echo "... individual_test"
	@echo "... initial_partitioner_base_test"
	@echo "... integration_tests"
	@echo "... interface_test"
	@echo "... k_way_fm_refiner_test"
	@echo "... kahypar"
	@echo "... kahypar_python"
	@echo "... kway_priority_queue_test"
	@echo "... label_propagation_functionality_test"
	@echo "... label_propagation_partitioner_test"
	@echo "... lazy_vertex_pair_coarsener_test"
	@echo "... libabcesop"
	@echo "... libabcsat"
	@echo "... louvain_test"
	@echo "... lsoracle"
	@echo "... math_test"
	@echo "... metrics_test"
	@echo "... mtx_to_hgr_converter_test"
	@echo "... mutation_test"
	@echo "... partitioner_test"
	@echo "... population_test"
	@echo "... priority_queue_test"
	@echo "... probability_table_test"
	@echo "... quotient_graph_block_scheduler_test"
	@echo "... random_partitioner_test"
	@echo "... regression_tests"
	@echo "... repeats_to_hgr_conversion_test"
	@echo "... sparse_map_test"
	@echo "... sparse_set_test"
	@echo "... sparsifier_test"
	@echo "... static_multi_dispatch_factory_test"
	@echo "... two_way_fm_refiner_test"
	@echo "... unit_tests"
	@echo "... vertex_pair_rater_test"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

